# ====================================================
# Makefile build 'Merge Sort project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -o bin/mergeSort -g

val:
	valgrind ../bin/mergeSort